### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by decuyperanthony** [hajareshyam/pdf-creator-node#10]
Hello! is it possible to add my css file ? and if yes. Where can i add it ? 
Thanks

**Comment by akwoprosper** [comment]
You can add your css file in the html template like any regular css file using a link tag

**Comment by hajareshyam** [comment]
Yes, You can add your custom CSS  in the HTML template

**Comment by blakecsharp** [comment]
Hello! I still cannot get this issue to resolve. I have linked my stylesheets but when I use the generator none of the style choices persist. I am using .scss style sheets - is that not supported?

**Comment by Sivaagamworks** [comment]
hi! i cannot import  my CSS on  html template

**Comment by Migue98** [comment]
In my case, the CSS wasn't loading because it could not load the images.
I mean, there was a error with my images when the PDF was created.
I hope this  be useful.
