### ISSUE TITLE
Text does not print on pdf

### ISSUE THREAD

**Issue by Baertie** [hajareshyam/pdf-creator-node#106]
I implemented everything like in the docs and locally everything works perfectly. But in production it does not.
I use docker. Anyone has an idea why the text is not showing?
[Baert-Arno (7).pdf](https://github.com/hajareshyam/pdf-creator-node/files/10287745/Baert-Arno.7.pdf)
[Drappier-Bert (2).pdf](https://github.com/hajareshyam/pdf-creator-node/files/10287746/Drappier-Bert.2.pdf)
 I have 2 pdfs one what it should be and one that i get in production.

**Comment by AkshaySeth94** [comment]
What was the fix you did?
