### ISSUE TITLE
Cannot use local file as css or image

### ISSUE THREAD

**Issue by giacomo-mambelli** [hajareshyam/pdf-creator-node#12]

**Comment by hajareshyam** [comment]
Hi,
You can use your local image and CSS in a pdf-creator-node package. 

**How to use -** 
I am assuming that you're using this package in your node server and every node server has its own URL - like http://localhost:4000, etc. Now if you want to use an image in this package then just use your server URL before image or CSS

**Example -** 
- Image - http://localhost:4000/assets/images/logo.jpg
- CSS - http://localhost:4000/assets/css/style.css
