### ISSUE TITLE
error while creating pdf, moves to catch block

### ISSUE THREAD

**Issue by Mrutyunjay1992** [hajareshyam/pdf-creator-node#14]
locally it works, when published the express code fails to create pdf in source directory of the application gives "epipe error"

**Comment by shusterhenry** [comment]
I have the same error. If you figure it out, let me know.

**Comment by rafaelkloss** [comment]
Any update on this ?

**Comment by hajareshyam** [comment]
Please try now

**Comment by junaidranjha** [comment]
same issue when deployed on aws elastic beanstalk
