### ISSUE TITLE
Add image to Header/Footer

### ISSUE THREAD

**Issue by rfogel** [hajareshyam/pdf-creator-node#16]
Hello.

I would like to know if it is possible to add images on header/footer, like we do on html. 

I have a config that is something like this:

`var document = {
    html: html,
    data: {
        headerImage: 'http://localhost:8080/test'
    },
    path: "./output.pdf"
};`

`var options = {
    format: "A2",
    orientation: "portrait",
    border: "0mm",
    header: {
        height: "45mm",
        //contents: '<img src="{{headerImage}}"></img>'
    },
}`

`contents: '<img src="{{headerImage}}"></img>'`
`contents: '<img src="http://localhost:8080/test"></img>'`

Both approaches wont work. 

Thanks for you help.

**Comment by haiduong2905** [comment]
Use one more a tag <img src="http://localhost:8080/test", style="display:none"> into tag body

**Comment by rfogel** [comment]
Yeah, I did that. A bit weird but OK. 

Thanks
