### ISSUE TITLE
Support for Images?

### ISSUE THREAD

**Issue by aeikman** [hajareshyam/pdf-creator-node#2]
Hello, this library is looking like a great solution, but I'm unable to display images in my output pdf. Any ideas?

Got it... Use the "file:///" prefix on the image's src.

**Comment by hajareshyam** [comment]
Hi,
You can add an image by using the image URL - 
Example - <img src="https://www.techjini.com/wp-content/uploads/2017/01/nodejs-logo.png" class="img-fluid" alt="Responsive image">

**Comment by cosacak** [comment]
Hello i could not display image on my created PDF.
I tried to add prefix "file:///" and I could not see your example image.

**Comment by devyzr** [comment]
I'm also unable to see the example, it seems the user's github is either down or inaccesible.

**Comment by tdodgehdai** [comment]
I got it working, but needed full file path. Like:
<img src="file:///Users/td/Documents/dev/server/images/pdf/graphTest.png"

I'm planning to pass in node's __dirname to flexibly get the full path.

**Comment by J-Meira** [comment]
i got it working only this way

`const bitmap = fs.readFileSync(__dirname+ "/pages/logo.jpg");
const logo = bitmap.toString('base64');
[...]
data: {
          logo: logo,//base64
[...]
<img width="100%" src="data:image/png;base64,{{../logo}}" alt="Logo" />`

i hope this help someone

**Comment by redwolfgang24** [comment]
> i got it working only this way
> 
> const bitmap = fs.readFileSync(__dirname+ "/pages/logo.jpg");
> const logo = bitmap.toString('base64');
> [...]
> data: {
> logo: logo,
> [...]
> `<img width="100%" src="data:image/png;base64,{{logo}}" alt="Logo" />`
> 
> i hope this help someone

This one works for me. Thanks @J-Meira

**Comment by aishvaryaverma** [comment]
> i got it working only this way
> 
> const bitmap = fs.readFileSync(__dirname+ "/pages/logo.jpg"); const logo = bitmap.toString('base64'); [...] data: { logo: logo, [...] `<img width="100%" src="data:image/png;base64,{{logo}}" alt="Logo" />`
> 
> i hope this help someone

works for me also, thanks

**Comment by ayoubben** [comment]
it work in locale, but not in production , it say that the document is damaged

**Comment by Skany** [comment]
I use ' src="file:///..."'  for <img> but also for other type of documents like <script> and I've been using the version 1.4.1 as they work there perfectly.

New versions don't work with this, is there any solution to use these local paths instead of links to webs?

**Comment by ayoubben** [comment]
@Skany I used an svg, and it works form me

**Comment by Fuseteam** [comment]
> Hi, You can add an image by using the image URL - Example - ![Responsive image](https://camo.githubusercontent.com/5215858a530341a32ae301ac316303763247dbb36af5ebcb95b2e0b52ffcda98/68747470733a2f2f7777772e746563686a696e692e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031372f30312f6e6f64656a732d6c6f676f2e706e67)

"responsive image" link is broken :(

**Comment by Fuseteam** [comment]
is this possibly related to #75 ?

**Comment by mmedhat1910** [comment]
> i got it working only this way
> 
> const bitmap = fs.readFileSync(__dirname+ "/pages/logo.jpg"); const logo = bitmap.toString('base64'); [...] data: { logo: logo, [...] `<img width="100%" src="data:image/png;base64,{{logo}}" alt="Logo" />`
> 
> i hope this help someone

Worked for me, thanks @J-Meira

**Comment by roseniltonreis** [comment]
> i got it working only this way
> 
> const bitmap = fs.readFileSync(__dirname+ "/pages/logo.jpg"); const logo = bitmap.toString('base64'); [...] data: { logo: logo, [...] `<img width="100%" src="data:image/png;base64,{{logo}}" alt="Logo" />`
> 
> i hope this help someone

This works perfectly!

**Comment by guidocaru** [comment]
> 

Thanks!!

**Comment by guidocaru** [comment]
> 

Thanks!!

**Comment by cnniss** [comment]
images don't work in header and footer - I was going mad at myself not being able to include an image :)

**Comment by nurmizwari** [comment]
why add image bro ?

**Comment by cnniss** [comment]
> why add image bro ?

because client wants his logo displayed in the header of each page. not something very uncommon.

**Comment by huzaifamk** [comment]
> i got it working only this way
> 
> const bitmap = fs.readFileSync(__dirname+ "/pages/logo.jpg"); const logo = bitmap.toString('base64'); [...] data: { logo: logo, [...] `<img width="100%" src="data:image/png;base64,{{logo}}" alt="Logo" />`
> 
> i hope this help someone

Great, this helps!
