### ISSUE TITLE
Image is not shown after convert pdf

### ISSUE THREAD

**Issue by IT222222** [hajareshyam/pdf-creator-node#34]
I'm using a nodejs. when I create an image from the buffer and insert into it HTML. it is not working. what is problem with it?
   
    //generate image
    const generatePDF147Timbre  = async (filePrefix, userId,tedString) => {

         try{
            var response =  await bwipjs.toBuffer({
                bcid:        'pdf417',       // Barcode type
                text:        tedString,    // Text to encode
                scale:       3,               // 3x scaling factor
                height:      5,  
                width:15,            // Bar height, in millimeters
                includetext: false,            // Show human-readable text
                textxalign:  'center',        // Always good to set this
        })

         fs.writeFileSync('F:\Node\barcode.png', response)
         return response.toString('base64')
      }catch(err)
      {
          console.log(err)
          return false;
      }
    }
    //generation pdf
        let barcodeBas64String  = await generatePDF147Timbre(filePrefix, userId, tedString)
        let options = {
            format: "A4",
            orientation: "portrait",
            border: "5mm",
            header: {
                height: "5mm",
            },
            footer: {
                height: "80mm",  
            }
        };
        
        let document = {
            html: "<img src=\"file:\\\F:\Node\barcode.png\" >", // or "<img src=\"data:image/gif;base64,"+barcodeBas64String+"\">
            data:{},
            path: pdfUrl,
            type: "",
        };
        
        try{
            await pdf
                    .create(document, options)
                    .then((res) => {
                        console.log(res);
                    })
                    .catch((error) => {
                        console.error(error);
                    });
        }catch(error)
        {
            console.log(error.message)
        }

**Comment by oscarshaitan** [comment]
having the same issue but only with local images if I use a online image works perfect!!!!!

**Comment by hajareshyam** [comment]
Please try with URL
If you running this project with a local host then use URL like http://localhost/barcode.png

**Comment by oscarshaitan** [comment]
I foudn that with local files I added the file:// before is workign for me

**Comment by boly38** [comment]
For a local file, I've used base64 way without issue:
```
const fs = require("fs");
const logoB64Content = fs.readFileSync('logo.jpg', {encoding: 'base64'});
const logoSrc = "data:image/jpeg;base64,"+logoB64Content;
const data = {
   logoSrc
}
``` 


and in the html template, I've `    <img src="{{logoSrc}}"/>`

**Comment by usujjualust** [comment]
I have tried all the above-mentioned solutions and it is not working for me

**Comment by shivang-pokar** [comment]
`const fs = require("fs");
const logoB64Content = fs.readFileSync('logo.jpg', {encoding: 'base64'});
const logoSrc = "data:image/jpeg;base64,"+logoB64Content;
const data = {
   logoSrc
}`

@boly38 Not working for me
