### ISSUE TITLE
#if conition in HTML ?

### ISSUE THREAD

**Issue by TeeeJaey** [hajareshyam/pdf-creator-node#35]
Can I write if conditions in HTML ?

```
    <ul>
      {{#each users}}
        {{#if this.id==2}}
            <li>Name: {{this.name}}</li>
            <li>Age: {{this.age}}</li>
            <br />
        {{/if}}
      {{/each}}
    </ul>
```

**Comment by TeeeJaey** [comment]
ERROR Receieved...

-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'EQUALS'
    at Parser.parseError (D:\Tejas\Work\Repository\MernPos\Server\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)

**Comment by HuitziDomingo** [comment]
> You forgot the word 'Cond' 

<li>Age: {{#ifCond this.age '===' '26'}}</li>
      <br />
      {{/ifCond}
