### ISSUE TITLE
Problem on {{page}} and {{pages}} evaluation

### ISSUE THREAD

**Issue by andreadinca1998** [hajareshyam/pdf-creator-node#68]
Hi,
I have a problem. When i use the tags {{page}} and {{pages}} in nodejs options(like this 
![image](https://user-images.githubusercontent.com/99720233/158412313-59f232df-d2c8-4b6b-9111-d8b500279a3a.png)
)they work perfectly. But if i use them in my html template inside a div with tag pageFooter(like this 
![image](https://user-images.githubusercontent.com/99720233/158412430-8fdd5b88-bbdf-4567-940e-46fb4b667bad.png)
) the module won't print the page number.

**Comment by benov84** [comment]
I have the same issue. Do you solve it?

**Comment by benov84** [comment]
Thank you very much!
