### ISSUE TITLE
Getting different PDF in production enviroment

### ISSUE THREAD

**Issue by treusfam** [hajareshyam/pdf-creator-node#79]
I made this app where you can generate a PDF. The content its only 1 page, 1 image and some data. In localhost everything is ok but after I deployed on Heroku the generated pdf is very different. 
On heroku the pdf generates 2 pages and the image is offset from where I put it ... any idea?

**Comment by krupalimakadiya** [comment]
@treusfam  
This issue you are facing due to this package depends on html-pdf package and i am facing the same issue with that package.
But i resolved using the font size. Mine was set to "em" and i changed them to "12px" and "14px" and now it's working.
Try changing the font size

**Comment by hajareshyam** [comment]
I will add this to the Readme file. Closing the issues.
