### ISSUE TITLE
Old module dependency in example folder -> security issues

### ISSUE THREAD

**Issue by cnniss** [hajareshyam/pdf-creator-node#85]
The module contains an example folder with own package.json file

Within the examples folder there is a dependency on an old version of pdf-creator-node
this raises security issues with
html-pdf @ 2.2.0 which raises high vulnerability 
json-schema @ 0.2.3 which raises critical vulnerability
minimist @ 1.2.5 which raises critical vulnerability

Can the dependency in the pdf-creator-node example folder be updated to the latest pdf-creator-node version so that security scans don't get these vulnerability warnings?

**Comment by hajareshyam** [comment]
Hi,
I have updated the dependency. Closing the issues
