### ISSUE TITLE
Css flexbox doesn't work 

### ISSUE THREAD

**Issue by MassiiNechiche** [hajareshyam/pdf-creator-node#90]
## Hello 
I tried using some css flexbox properties like justify content and the result is not what expected ! so i had to flow stuff left & right.
cheers

**Comment by Migue98** [comment]
Same issue :(
Some trick??

**Comment by sbn111** [comment]
Usualy Flex box not supported in pdf generator
Use float or table method to overcome

**Comment by Migue98** [comment]
Thanks.
I already used tables.
